name: CICD workflow
on:
  push:
env:
  WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
  CICD_REPO_PATH: ${{ secrets.CICD_REPO_PATH }}
jobs:
  ci-projects:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    outputs:
      projects: ${{ steps.project-step.outputs.projects }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '2'
      - name: fetch main
        run: |
          git fetch origin main --depth 1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install workflow dependencies
        run: |
          pip install requests GitPython
      - id: api-step
        name: Check change in api
        run: |
          projects=$(python ./monorepo/projects_updated.py -c "origin/main")
          echo "projects=$projects" >> "$GITHUB_OUTPUT"

  ci:
    needs:
      - ci-project
    strategy:
      matrix:
        projects: ${{ needs.ci-projects.outputs.projects }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        id: python-cache
        with:
          python-version: '3.10'
          cache: pip
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        if: ${{ inputs.called == 'true' }}
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:morpheus-server"
          build-args: |
            BUILD_ENV=copy
          push: true
          tags: monadicalsas/morpheus-api:${{ github.run_id }}
  
#############################################################################################################
### CD - jobs
#############################################################################################################
  cd:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    outputs:
      api: ${{ steps.api-step.outputs.api }}
      collaborative: ${{ steps.collaborative-step.outputs.collaborative }}
      frontend: ${{ steps.frontend-step.outputs.frontend }}
      workerray: ${{ steps.worker-ray-step.outputs.workerray }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '2'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install workflow dependencies
        run: |
          pip install requests GitPython
      - id: api-step
        name: Check change in api
        run: |
          api=$(python ./monorepo/cicd.py --project morpheus-server)
          echo "api=$api" >> "$GITHUB_OUTPUT"
      - id: collaborative-step
        name: Check change in collaborative
        run: |
          collaborative=$(python ./monorepo/cicd.py --project morpheus-collaborative)
          echo "collaborative=$collaborative" >> "$GITHUB_OUTPUT"
      - id: frontend-step
        name: Check change in frontend
        run: |
          frontend=$(python ./monorepo/cicd.py --project morpheus-client)
          echo "frontend=$frontend" >> "$GITHUB_OUTPUT"
      - id: worker-ray-step
        name: Check change in worker ray
        run: |
          workerray=$(python ./monorepo/cicd.py -c "origin/main" --project morpheus-worker-ray)
          echo "workerray=$workerray" >> "$GITHUB_OUTPUT"

  cd-api:
    if: needs.cd.outputs.api == 'true'
    needs:
      - cd
    uses: ./.github/workflows/cd-api.yaml
    secrets: inherit
  cd-frontend:
    if: needs.cd.outputs.frontend == 'true'
    needs:
      - cd
    uses: ./.github/workflows/cd-frontend.yaml
    secrets: inherit
  cd-collaborative:
    if: needs.cd.outputs.collaborative == 'true'
    needs:
      - cd
    uses: ./.github/workflows/cd-collaborative.yaml
    secrets: inherit
  cd-worker-ray:
    if: needs.cd.outputs.workerray == 'true'
    needs:
      - cd
    uses: ./.github/workflows/cd-worker-ray.yaml
    secrets: inherit
